language: node_js

branches:
  except:
    - /^build-[0-9a-z\-]*/

cache:
  directories:
    - node_modules

services:
  - docker

node_js:
  - "8"
  - "9"

script:
  - yarn test
  - yarn coverage
  - yarn generate-docs

after_success:
  # CREATE GIT TAG
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git commit -m "Set build VERSION number" public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GITHUBKEY@github.com/maxemiliang/musicSync $GIT_TAG > /dev/null 2>&1

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUBKEY  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: docs
  on:
    branch: master


sudo: false
