language: node_js

branches:
  except:
    - /^build-[0-9a-z\-]*/

cache:
  yarn: true
  directories:
    - node_modules

services:
  - docker

sudo: required

node_js:
  - "8"
  - "9"

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - yarn install

script:
  - yarn clean-test
  - yarn coverage

after_success:
  # CREATE GIT TAG
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git commit -m "Set build VERSION number" public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GITHUBKEY@github.com/maxemiliang/musicSync $GIT_TAG > /dev/null 2>&1

before_deploy:
  # create docs 
  - yarn generate-docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUBKEY  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: docs
  on:
    branch: master
    node: 9


