version: '3'

services:
  musicsync:
    container_name: musicsync
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
    entrypoint: npm start
    tty: true
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:secret@mysql/
      PORT: 8085
      INITALIZE_DB: 1
    ports:
      - '8085:8085'
  mysql:
    image: mariadb:latest
    container_name: musicsync-db
    volumes:
      - musicsync-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'

volumes:
  musicsync-db:
